import type { AgentTransformer, TransformResult } from '../transformer.js';
import { WORKFLOW_SKILLS, simplifyFrontmatter } from '../transformer.js';
import { writeTextFile, fileExists, removeFile } from '../../utils/fs.js';
import path from 'path';

export class AntigravityTransformer implements AgentTransformer {
  transform(skillName: string, content: string): TransformResult {
    if (WORKFLOW_SKILLS.has(skillName)) {
      return {
        targetDir: 'workflows',
        targetName: `${skillName}.md`,
        content: simplifyFrontmatter(content),
        flat: true,
      };
    }

    return {
      targetDir: skillName,
      targetName: 'SKILL.md',
      content,
      flat: false,
    };
  }

  async postInstall(projectDir: string): Promise<void> {
    const rulesDir = path.join(projectDir, '.agent', 'rules');

    const guardrailsContent = `# AI Factory Guardrails

## Project Conventions

- Follow existing code style and patterns in the project
- Use conventional commits format for all commit messages
- Always check for existing implementations before creating new ones
- Prefer editing existing files over creating new ones
- Run tests after making changes when test infrastructure exists

## Skill Usage

- Use \`/aif-explore\` to think through ideas before planning — no implementation, just exploration
- Use \`/aif-plan\` for new features — creates branch, plan, and tasks
- Use \`/aif-fix\` for bug fixes — analyzes, fixes, suggests tests
- Use \`/aif-commit\` for commits — follows conventional commits
- Use \`/aif-implement\` to execute plans step by step
- Use \`/aif-review\` before merging — checks code quality

## Safety

- Never commit secrets, tokens, or credentials
- Never force-push to main/master branches
- Always create feature branches for new work
`;

    const conventionsContent = `# AI Factory Conventions

## Workflow Structure

AI Factory organizes skills into three categories:

### Workflows (.agent/workflows/)
Action-oriented skills that execute specific tasks:
- \`aif-explore.md\` — Think through ideas, investigate problems
- \`aif-plan.md\` — Plan and develop new features
- \`aif-fix.md\` — Fix bugs with structured approach
- \`aif-implement.md\` — Execute plans step by step
- \`aif-commit.md\` — Create conventional commits
- \`aif-review.md\` — Code review checklist
- \`aif-ci.md\` — CI/CD pipeline setup

### Skills (.agent/skills/)
Knowledge-based skills providing guidelines and patterns:
- \`best-practices/\` — Code quality standards
- \`architecture/\` — Architecture decision records
- Project-relevant skills generated by \`/aif\`

### Rules (.agent/rules/)
Always-active guardrails and conventions that apply to every interaction.

## Naming Convention

- Workflow files: \`aif-{action}.md\` (flat files)
- Skill directories: \`{skill-name}/SKILL.md\` (with supporting files)
- Rule files: \`aif-{rule-name}.md\`
`;

    await writeTextFile(path.join(rulesDir, 'aif-guardrails.md'), guardrailsContent);
    await writeTextFile(path.join(rulesDir, 'aif-conventions.md'), conventionsContent);
  }

  async cleanup(projectDir: string, skillsDir: string): Promise<void> {
    const configDir = path.dirname(skillsDir);
    const workflowsDir = path.join(projectDir, configDir, 'workflows');
    for (const workflow of WORKFLOW_SKILLS) {
      const workflowFile = path.join(workflowsDir, `${workflow}.md`);
      if (await fileExists(workflowFile)) {
        await removeFile(workflowFile);
      }
    }

    for (const ruleFile of ['aif-guardrails.md', 'aif-conventions.md']) {
      const rulePath = path.join(projectDir, configDir, 'rules', ruleFile);
      if (await fileExists(rulePath)) {
        await removeFile(rulePath);
      }
    }
  }

  getWelcomeMessage(): string[] {
    return [
      '1. Open Antigravity in this directory',
      '2. Action skills installed as workflows in .agent/workflows/ (flat files)',
      '3. Knowledge skills installed in .agent/skills/ (directories)',
      '4. Rules installed in .agent/rules/ (guardrails and conventions)',
      '5. Run /aif to analyze project and generate project-relevant skills',
    ];
  }
}
